### ISSUE TITLE
Resistor values

### ISSUE THREAD

**Issue by ka8nbg** [jonsag/piSchoolBell#1]
Real quick question, I see you are using 4 1k and 4 10k resistors, but the drawing shows the same color code for all 8. Which ones need to go to where? Is it documented somewhere?  Thanks in advanced.

**Comment by jonsag** [comment]
Actually, of you look carefully on the fritz the resistors are different coloured.
The ones to the left of each switch are brown/black/red, and the ones to the right are  brown/black/orange.
So the order should be:
VCC-->10k-->switch-->1k-->input
and the other switch leg goes straight to GND.
If you want you can actually skip the 1k resistors. These are just for protection.
The 10k are pullups.
Good luck
/jon

**Comment by ka8nbg** [comment]
Wow, I am getting more and more color blind.  Thanks for the
clarification!!!!   Plan on getting this built this weekend.  Have a great
Christmas!!!!

**Comment by jonsag** [comment]
It was a little hard to see. Wasn't sure myself until I clicked the components in the real fritz.
Are you planning to use it in a school? I have mine running in the school where I work. The old mechanical clock was running five-ten minutes fast every day and too expensive to repair.
Happy christmas for you too.
/jon

**Comment by ka8nbg** [comment]
Yes, our church just started at school this past semester and was looking for an outside bill. I’m looking to get this up and running this next week and installed. We bought one of those fire alarm bells that runs on 110 VAC. By the way, you mentioned about a PC board that you have for this project, do you still have more of those? I have a real issue with creating breadboards and never getting them converted over, If you know what I mean. Here’s an example of one lesson production. Not very proud of the final product but it works very well.

**Comment by jonsag** [comment]
I soldered it up on an experiment board and this is how it runs now.
Didn't make a PCB for this. Started out making one in Eagle CAD, but never finished with the routing. You can now find it in the 'Documents' directory if you would like to finish it.
For some of my projects I have ordered PCBs from jlcpcb.com. 10 boards for $2+shipping! Reasonably fast shipping and good finish.

**Comment by jonsag** [comment]
Did some routing on the Eagle files in documentation and uploaded a Gerber-file for ordering PCBs.
Of course not tested, and perhaps you can do a better job.
Also added etching masks if you would like to make some PCBs yourself.

**Comment by ka8nbg** [comment]
Awesome. Will take a look at it. Thanks again.

**Comment by ka8nbg** [comment]
Jon, I have installed the OS and the software from the GIT repository. Have
it configured, have not been able to log into the web page using
piSchoolBell and the password that I created. Any idea what I am missing?

**Comment by jonsag** [comment]
Sorry for the late reply. The holidays and all you know...
You ran 'www-secure-setup.sh'?
OK, temporarily comment out the four lines:  
AuthName "piSchoolBell"
AuthType Basic
AuthUserFile /home/pi/bin/piSchoolBell/.htpasswd
require valid-user
in '/var/www/piSchoolBell/.htaccess'
Can you load the pages now?
If yes, then uncomment them.
Try to add another user:
`sudo htpasswd -c /home/pi/bin/piSchoolBell/.htpasswd`
Now try to login with that user
