### ISSUE TITLE
username and password to access web interface.

### ISSUE THREAD

**Issue by DanielProwse** [jonsag/piSchoolBell#2]
Hi

I am wanting to confirm what the username and password should be to access the web interface localhost:8080?

I have tried the db user but it is not authenticating.

Hope you can help.

**Comment by jonsag** [comment]
Hi

If you followed the Readme.md the username is 'admin'.
The password is set when you run 'www-secure-setup.sh'.
>$ sudo /home/pi/piSchoolBell/www-secure-setup.sh

If you have set up the password and forgot it, simply remove
'/home/pi/bin/piSchoolBell/.htpasswd' and set passwd again.
>$ sudo rm /home/pi/bin/piSchoolBell/.htpasswd
>$ sudo htpasswd -c /home/pi/piSchoolBell/.htpasswd admin

Check that you have a file, '/var/www/piSchoolBell/.htaccess' containing
the following:
AuthName "piSchoolBell"
AuthType Basic
AuthUserFile /home/pi/bin/piSchoolBell/.htpasswd
require valid-user

DirectoryIndex index.py

Hope this helps
/jon



------------------------------------------------------------------------------
Jon Sagebrand

Jonix
Blacksta 6
611 95 Nyköping

***@***.***

070-694 67 34
------------------------------------------------------------------------------


Den tors 6 juli 2023 kl 08:16 skrev DanielProwse ***@***.***>:

**Comment by ka8nbg** [comment]
Thanks for the reply. I ended up using something else, but will look into
going back to this.  Thanks.
